import puppeteer from "npm:puppeteer-core@23";
const b = await puppeteer.launch({executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", headless: "new", args: ["--hide-scrollbars"]});
const p = await b.newPage();
await p.setViewport({width: 1440, height: 1000});
await p.goto("http://localhost:4780/experience/?noanim=1&e=" + Date.now(), {waitUntil: "domcontentloaded", timeout: 60000});
await new Promise(r => setTimeout(r, 1500));
await p.evaluate(() => { const secs = document.querySelectorAll("main > section"); secs[1].scrollIntoView({block: "start"}); scrollBy(0, -100); });
await new Promise(r => setTimeout(r, 800));
await p.screenshot({path: "page-exp-sec2.png"});
await p.evaluate(() => scrollTo(0, 400));
await new Promise(r => setTimeout(r, 600));
await p.screenshot({path: "page-exp-sec1.png"});
await b.close(); console.log("ok");
